### ISSUE TITLE
command is not working anymore

### ISSUE THREAD

**Issue by Master244** [madnificent/ember-nginx-docker#2]
Unable to find image ' -p:latest' locally
Invalid repository name ( -p), only [a-z0-9-_.] are allowed

**Comment by madnificent** [comment]
Can you provide the complete command which you used to run this container?  Thanks

**Comment by Master244** [comment]
actually yours from the readme.md

**Comment by Master244** [comment]
im trying to run a single app through nginx to do some testing with prerender.io for Robots. But I'm really having a hard time getting nginx to serve my app. Your setup should do the trick but I don't seem to get it to work.

**Comment by madnificent** [comment]
Command updated in current master (76ee32c118f1a932a966b38ba3d03f5c3cc07cdb).  There had to be newlines after each `\`.  Or you remove the `\` symbols in the run command.

**Comment by Master244** [comment]
The command works now and I can build it and its running but it doesn't show anything.

Is it possible to use this configuration without a backend? My app connects to a API on the web not locally. 

docker run -d -p 8080:80 --volume /Users/mitchell/Documents/Work/ServiceBook/app/servicebook-public-website/:/app  madnificent/ember-nginx

is the command I ran, I left out the backend part

**Comment by madnificent** [comment]
Does the `/Users/mitchell/Documents/Work/ServiceBook/app/servicebook-public-website/` folder contain the dist folder of your ember app?  It should be the dist folder which is the result of `ember build`.  Is that the case, or is it a different folder?

**Comment by Master244** [comment]
it does but even when I change it back to dist and remove and rebuild everything again and I try to visit the ip adress it doens't work. Any idea's? My plan is just to build a new ember project and serve it through nginx so I can visit the app in the browser or choose to build an ember app without the CLI. 

Thanks a lot already for your reactions so far :)

**Comment by madnificent** [comment]
I have just successfully ran the docker with the following steps:

```
  docker pull madnificent/ember-nginx

  cd /home/madnificent/code/ember/tst
  ember new i-can-host-this

  ember build

  docker run --name ember-nginx-test -p 8080:80 --link test-virtuoso:backend -v /home/madnificent/code/ember/tst/i-can-host-this/dist/:/app/ madnificent/ember-nginx
```

The link to the backend service is required, otherwise nginx will fail to start (you should see that in the log of the docker).  You should then get the index page when you browse to `http://localhost:8080/`.  It may be that you need to use the IP address of the dockermachine instead if you are running this on your mac.  I'm not certain how transparent docker is on that environment.

Can you try these commands and check if that yields a response?

UPDATE: changed dr to docker

**Comment by Master244** [comment]
I get:

Get https://index.docker.io/v1/repositories/madnificent/ember-nginx/images: dial tcp: lookup index.docker.io on 172.16.0.1:53: read udp 172.16.0.1:53: i/o timeout

when running the pull command. Obviously the cd command will fail because the directory doesn't exist. 

To add i'm running docker-machine on mac 

To test every new try I delete my vm and create a new one with create -d virtualbox name, I set-up the variables with the env command etc. I am able to see the standard NGINX welcome page with the nginx image from docker hub. 

I tried to run the dr command but it does not know 'dr' so I tried to run it with docker which resulted in: Could not get container for test-virtuoso

I also tried to delete the backend part from your config and try and serve the /app folder but no luck :( 

The way I want to set this up ideally is to have a Dockerfile with a compose file so I can spawn multiple instances of the app. ( this is for socket testing ). But my first goal was to actually get nginx to serve the dist folder but that turned out to be a pain for a quite some time now :P

**Comment by madnificent** [comment]
I indeed have an alias for `docker` named `dr`, my bad.

Given your setup, I think the following should give you a basic running ember application.  This is somewhat guessing based on your setup.

```
  cd /Users/mitchell/Documents/
  ember new i-can-host-this
  # new ember app is built and dependencies are being created here
  cd i-can-host-this
  ember build
  # ember is building the application here, it will be stored in /Users/mitchell/Documents/i-can-host-this/dist

  # do whatever you need to do to setup a new docker machine
  cat /Users/mitchell/Documents/i-can-host-this/dist/index.html
  # verify the above outputs an HTML page so the app is there from whatever shell you'll run the docker run command from (I hope this is transparent).
  docker run -d --name mock-backend nginx # any server that keeps running should be ok
  docker run -d --name ember-nginx-test -p 8080:80 --link mock-backend:backend -v /Users/mitchell/Documents/i-can-host-this/dist/:/app/ madnificent/ember-nginx
```

And then opening http://localhost:8080 in the browser.

If you don't get the right page, paste whatever `docker logs ember-nginx-test` gives you after trying to fetch the page in here please.  Thanks.

**Comment by Master244** [comment]
I used docker-machine ls in the end to check the ip and it works like a charm :D thank you very much!

I was just wondering then how do I get your commands after the docker run in the dockerfile so I can run the container with compose?

**Comment by Master244** [comment]
what happend :O is your repo not available anymore?

An error occurred trying to connect: Post https://192.168.99.101:2376/v1.20/containers/create?name=mock-backend: dial tcp 192.168.99.101:2376: i/o timeout

**Comment by Master244** [comment]
I reinstalled docker it works now I guess updating to the docker toolbox wasn't such a good idea
